### ISSUE TITLE
Cannot declare class Sentry Running: php artisan config:cache

### ISSUE THREAD

**Issue by remko-key** [OFFLINE-GmbH/oc-sentry-plugin#2]
I don't know if this an OctoberCMS bug or the Sentry plugin. I installed the plugin using composer on OctoberCMS **2.1.11** with Laravel Framework **6.20.35**

When I run: **php artisan config:cache** this error popups:

**_In Plugin.php line 33:                                                                   
  Cannot declare class Sentry, because the name is already in use_**  
                                                                   
This is the code on line 33:
```
    public function register()
    {
        class_alias(\OFFLINE\Sentry\Classes\SentryFacade::class, 'Sentry');
    }

```

Removing the line **class_alias(\OFFLINE\Sentry\Classes\SentryFacade::class, 'Sentry');** solves the error but isn't the solution 😃

**Comment by martijngastkemper** [comment]
I've the same issue when running unit tests. When `OFFLINE\Sentry\Plugin->register()` is called multiple times the `Cannot declare class Sentry...` error shows up. I've opened a PR which fixes the problem in my case. No clue if it's the right solution.
