### ISSUE TITLE
Sentry perfomance support

### ISSUE THREAD

**Issue by prhost** [OFFLINE-GmbH/oc-sentry-plugin#3]
Hi,

Do you know if the plugin has Sentry performance functionality? I did not find where to configure.

https://docs.sentry.io/product/performance/

**Comment by tobias-kuendig** [comment]
You probably have to add the configuration around here: https://github.com/OFFLINE-GmbH/oc-sentry-plugin/blob/master/Plugin.php#L138

If you can get it working, we could move the sentry config to a `config.php` file that allows you to configure everything.

**Comment by prhost** [comment]
I did some tests here, looked at the sentry laravel repository, and I believe the problem is a little more complex to solve.

As the plugin does not use sentry's ServiceProvider, this part where I defined the settings in the plugin, is similar to laravel, but it seems to me that there are many more things to implement, I just tried to copy the settings, but I saw that it handles some particularly before running sentry, one of them is this performance part.

Here are some interesting parts of their repository:

https://github.com/getsentry/sentry-laravel/blob/2.12.0/src/Sentry/Laravel/ServiceProvider.php#L245-L247
https://github.com/getsentry/sentry-laravel/blob/2.12.0/src/Sentry/Laravel/BaseServiceProvider.php#L47-L52
https://github.com/getsentry/sentry-laravel/blob/2.12.0/config/sentry.php#L53

**Comment by tobias-kuendig** [comment]
Version 3.0 of this plugin is a lot closer to the original implementation and should allow you to configure these settings in the standard Sentry way (using the config/sentry.php) file.
